language: node_js
node_js:
  - '7.7'
script: npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
cache: yarn
addons:
  ssh_known_hosts: api.prs.ggpark.net
