language: node_js
node_js:
  - '7.7'
script: npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
cache:
  directories:
    - node_modules
addons:
  ssh_known_hosts: work.maid.cat
